### ISSUE TITLE
Feil enkoding i emne får hele søket til å tryne

### ISSUE THREAD

**Issue by magnuswatn** [magnuswatn/sertifikatsok#132]
Fører til følgende feil:

```
2022-05-23 11:39:14,896 ERROR sertifikatsok.web An exception occured: (70b0c5ce-497c-498b-9986-8b60861fb245)
Traceback (most recent call last):
  File "/opt/sertifikatsok/api/sertifikatsok/web.py", line 23, in error_middleware
    return await handler(request)
  File "/opt/sertifikatsok/api/sertifikatsok/web.py", line 49, in correlation_middleware
    response = await handler(request)
  File "/opt/sertifikatsok/api/sertifikatsok/logging.py", line 80, in wrapper
    return_value = await func(*args, **kwargs)
  File "/opt/sertifikatsok/api/sertifikatsok/web.py", line 104, in api_endpoint
    search_response = await certificate_search.get_response()
  File "/opt/sertifikatsok/api/sertifikatsok/search.py", line 367, in get_response
    return CertificateSearchResponse.create(self)
  File "/opt/sertifikatsok/api/sertifikatsok/search.py", line 379, in create
    cert_sets = QualifiedCertificateSet.create_sets_from_certs(search.results)
  File "/opt/sertifikatsok/api/sertifikatsok/qcert.py", line 301, in create_sets_from_certs
    (cert_set[0].print_subject() != cert.print_subject())
  File "/opt/sertifikatsok/api/sertifikatsok/qcert.py", line 127, in print_subject
    for field in self.cert.subject:
ValueError: error parsing asn1 value: ParseError { kind: InvalidValue, location: ["subject"] }
```

Cryptography parser tydeligvis ikke emnet før man bruker det, så fiksen fra #22 treffer ikke.

Enkel løsning er bare å aksessere emnet under initiell parsing av sertifikatet. Tror det blir cachet, så burde ikke ha noe å si på ytelsen.

**Comment by magnuswatn** [comment]
Dette er fikset, men kunne nok vært gjort smoothere. Laget https://github.com/magnuswatn/sertifikatsok/issues/156 for å evt. forbedre.
