### ISSUE TITLE
Ustabilitet

### ISSUE THREAD

**Issue by magnuswatn** [magnuswatn/sertifikatsok#192]
Etter en oppetid på 7 dager, 15 timer og 45 minutter, hvor det ble gjort 437 queries (351 prod enterprise, 79 prod person og 7 test enterprise) begynte appen å trøble.

Søk hang, og det virker som om den feilet mot alle ldap-katalogene med ca. samme feil:

```
2023-01-09 09:55:52,775 ERROR sertifikatsok.search Error during ldap query against 'ldap.buypass.no: dc=Buypass,dc=no,CN=Buypass Class 3 CA 3' (91e8c740-9109-457c-af98-cb8fa90bd646)
Traceback (most recent call last):
  File "/opt/sertifikatsok/api/sertifikatsok/search.py", line 351, in query_ca
    await self.do_ldap_search(
  File "/opt/sertifikatsok/api/sertifikatsok/search.py", line 386, in do_ldap_search
    async with client.connect(is_async=True, timeout=LDAP_TIMEOUT) as conn:
  File "/opt/sertifikatsok/venv/lib/python3.10/site-packages/bonsai/asyncio/aioconnection.py", line 25, in __aenter__
    return await self.__open_coro
  File "/opt/sertifikatsok/venv/lib/python3.10/site-packages/bonsai/asyncio/aioconnection.py", line 59, in _poll
    raise exc
  File "/opt/sertifikatsok/venv/lib/python3.10/site-packages/bonsai/asyncio/aioconnection.py", line 54, in _poll
    return await asyncio.wait_for(fut, timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/sertifikatsok/venv/lib/python3.10/site-packages/bonsai/asyncio/aioconnection.py", line 40, in _ready
    res = super().get_result(msg_id)
bonsai.errors.ConnectionError: Can't contact LDAP server. (0xFFFF [-1])
```

Forsøkene tok flere minutter, lang mer enn angitt timeout-verdi.

Dette er ugreit, har ikke vært slik tidligere. Mest sannsynlig innført i den nyeste versjonen av bonsai. Prøv å gjenskap og evt. lag bug upstream. Vurder om vi bør legge på en egen timeout på taskene, i tillegg til den vi setter på bonsai.

TIdslinje:
Boot: 2023-01-01 16:57:13,188
Siste ok query: 2023-01-09 08:38:50,293
Første feil: 2023-01-09 08:42:21,490
Boot: 2023-01-09 10:22:53,347
Første OK query: 2023-01-09 10:23:06,004

**Comment by magnuswatn** [comment]
Her virket det som om at problemet oppstod hvis oppkobling ble hengendes mot én av LDAP-serverne, så stokka det seg helt for bonsai, og alt begynte å henge. Bonsai har hatt problemer med TCP SYN timeout tidligere, så ikke ukjent problemstilling. Altså ikke relatert til oppetid e.l.. Det er rett og slett ikke lett å finne den nøyaktige kombinasjonen av opsjoner som får den eldgamle C-koden til OpenLDAP til å oppføre seg...

Utfordringen ble løst av #279, siden bonsai ikke lenger er i bruk. Ser oppkobling timer ut fra tid til annen nå også, men nå håndteres alt som det skal, og det times ut som det skal.
