### ISSUE TITLE
Støtte for SEID v2.0

### ISSUE THREAD

**Issue by magnuswatn** [magnuswatn/sertifikatsok#37]
Buypass har begynt å utstede virksomhetssertifikater hvor organisasjonsnummeret kun ligger i Organization Identifier-feltet, og emnet er da uten serialNumber-feltet. Dette er eIDAS-greier, beskrevet i [sertifikatprofilene deres](https://www.buypass.no/sikkerhet/ca-dokumentasjon-juridisk/_/attachment/download/383fe9ba-9de6-49d5-b6af-337dff2bbfae:b1d0adfb8610d7886db47ab927bbb7abdb54a42e/CertProfiles_Cl3_v15-new.pdf).

Dette takles p.t. dårlig:

```
2020-08-06 19:55:55,816 ERROR sertifikatsok.web An exception occured: (e0b55a0c-3afc-4849-9d98-3758925d40bf)
Traceback (most recent call last):
  File "/opt/sertifikatsok/repo/api/sertifikatsok/web.py", line 24, in error_middleware
    return await handler(request)
  File "/opt/sertifikatsok/repo/api/sertifikatsok/web.py", line 50, in correlation_middleware
    response = await handler(request)
  File "/opt/sertifikatsok/repo/api/sertifikatsok/logging.py", line 80, in wrapper
    return_value = await func(*args, **kwargs)
  File "/opt/sertifikatsok/repo/api/sertifikatsok/web.py", line 105, in api_endpoint
    search_response = await certificate_search.get_response()
  File "/opt/sertifikatsok/repo/api/sertifikatsok/search.py", line 247, in get_response
    return CertificateSearchResponse.create(self)
  File "/opt/sertifikatsok/repo/api/sertifikatsok/search.py", line 259, in create
    cert_sets = QualifiedCertificateSet.create_sets_from_certs(search.results)
  File "/opt/sertifikatsok/repo/api/sertifikatsok/qcert.py", line 261, in create_sets_from_certs
    cert_sets.append(cls.create(cert_set))
  File "/opt/sertifikatsok/repo/api/sertifikatsok/qcert.py", line 208, in create
    org_number, underenhet = main_cert.get_orgnumber()
  File "/opt/sertifikatsok/repo/api/sertifikatsok/qcert.py", line 129, in get_orgnumber
    0
IndexError: list index out of range
```

Dette bør håndteres. Litt usikker på om orgnummeret bør hentes fra Organization Identifier-feltet eller ikke.

**Comment by magnuswatn** [comment]
https://buypassdev.atlassian.net/wiki/spaces/BCA/pages/2182479873/Endringer+i+Buypass+personsertifikater+og+virksomhetssertifikater

**Comment by magnuswatn** [comment]
Det som må gjøres her blir da:
* Hente orgnummer fra Organization Identifier-feltet
* Legge inn trust for de nye CA-ene til Buypass, og evt. nye OID-er.

Men jeg ser ingen attributter i katalogen til Buypass som kan brukes til å søke opp disse nye sertifikatene basert på orgnummer, så det er jo litt SNEDIG. Håpløst om det forsvinner, så må nesten høre med de om det.

**Comment by magnuswatn** [comment]
* https://github.com/magnuswatn/sertifikatsok/commit/73071692b9218726e02b4f92171f324270061148
* https://github.com/magnuswatn/sertifikatsok/commit/cec9578f900039a173ced223f110d83de27b1b98

**Comment by magnuswatn** [comment]
Det som gjenstår her nå er å også søke i organizationIdentifier når det søkes på orgnr.

**Comment by magnuswatn** [comment]
Etter litt frem og tilbake så søkes det nå også i organizationIdentifier når man søker etter ognr.

**Comment by magnuswatn** [comment]
Det som har gjenstått her er håndtering av søk på `NTRNO-\d{9}`. Etter mye indre diskusjon endte det opp med at slike søk blir håndtert likt som søk på kun orgnr, dvs. at vi søker på både SEID1- og SEID2-format. Dette etter prinsippet om å prøve å være mest mulig hjelpsom og finne mest mulig, og for å matche håndteringen av personlige serienummer. Skulle noen ønske å kun finne SEID2-sertifikat burde det være grei skuring å ctrl+f etter det på resultatsiden, evt. så vil det bli muliggjort av #5, om den noengang lander.

Implementert i  [1f75566](https://github.com/magnuswatn/sertifikatsok/commit/1f755660a6a15496f5143acde9f181c669ec51ac)
